# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :cpl do
    # Create a custom keychain for code signing
    create_keychain(
      name: 'keychain',
      password: 'password',
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    match(
      type: "appstore",
      keychain_name: 'keychain',
      keychain_password: 'password',
      readonly: true
    )
    build_app(scheme: 'finance')
    upload_to_testflight
  end

  desc "Description of what the lane does"
  lane :marriage do
    deliver(
      build_number: latest_testflight_build_number.to_s,
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end
end
